"""initial migration

Revision ID: 9cd6c831dc17
Revises: 
Create Date: 2025-01-07 15:12:57.535393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cd6c831dc17'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('place_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_place_categories_id'), 'place_categories', ['id'], unique=False)
    op.create_table('place_labels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_place_labels_id'), 'place_labels', ['id'], unique=False)
    op.create_table('place_menu_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_place_menu_categories_id'), 'place_menu_categories', ['id'], unique=False)
    op.create_table('place_places',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('logo', sa.String(), nullable=True),
    sa.Column('video', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_place_places_id'), 'place_places', ['id'], unique=False)
    op.create_index(op.f('ix_place_places_name'), 'place_places', ['name'], unique=False)
    op.create_table('place_association_categories',
    sa.Column('place_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['place_categories.id'], ),
    sa.ForeignKeyConstraint(['place_id'], ['place_places.id'], ),
    sa.PrimaryKeyConstraint('place_id', 'category_id')
    )
    op.create_table('place_association_labels',
    sa.Column('place_id', sa.Integer(), nullable=False),
    sa.Column('label_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['label_id'], ['place_labels.id'], ),
    sa.ForeignKeyConstraint(['place_id'], ['place_places.id'], ),
    sa.PrimaryKeyConstraint('place_id', 'label_id')
    )
    op.create_table('place_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('place_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['place_id'], ['place_places.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_place_images_id'), 'place_images', ['id'], unique=False)
    op.create_table('place_menu_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('place_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['place_menu_categories.id'], ),
    sa.ForeignKeyConstraint(['place_id'], ['place_places.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_place_menu_items_id'), 'place_menu_items', ['id'], unique=False)
    op.create_table('place_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('place_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['place_id'], ['place_places.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_place_services_id'), 'place_services', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_place_services_id'), table_name='place_services')
    op.drop_table('place_services')
    op.drop_index(op.f('ix_place_menu_items_id'), table_name='place_menu_items')
    op.drop_table('place_menu_items')
    op.drop_index(op.f('ix_place_images_id'), table_name='place_images')
    op.drop_table('place_images')
    op.drop_table('place_association_labels')
    op.drop_table('place_association_categories')
    op.drop_index(op.f('ix_place_places_name'), table_name='place_places')
    op.drop_index(op.f('ix_place_places_id'), table_name='place_places')
    op.drop_table('place_places')
    op.drop_index(op.f('ix_place_menu_categories_id'), table_name='place_menu_categories')
    op.drop_table('place_menu_categories')
    op.drop_index(op.f('ix_place_labels_id'), table_name='place_labels')
    op.drop_table('place_labels')
    op.drop_index(op.f('ix_place_categories_id'), table_name='place_categories')
    op.drop_table('place_categories')
    # ### end Alembic commands ###
